name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  linting:
   uses: woped/devops/.github/workflows/linting.yaml@main
  testing_pytest:
    uses: woped/devops/.github/workflows/testing_pytest.yaml@main
  sonar_python:
    needs: testing_pytest
    uses: woped/devops/.github/workflows/sonar_python.yaml@main
    secrets: inherit
