name: WordNet Python Mircoservice Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MAJOR_VERSION: 2
  MINOR_VERSION: 0
  MICRO_VERSION: 0
  IMAGE_NAME: word-net-microservice
  IMAGE_REPOS: woped

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REPOS }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_REPOS }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}
            ${{ env.IMAGE_REPOS }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
            ${{ env.IMAGE_REPOS }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.MICRO_VERSION }}
